services:
  synthrad:
    build:
      context: .
    volumes:
      # path to data directory
      - /local/directory:/data
      # path to pre-processing code
      - ../:/code
    command: tail -F anything
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 'all'
            capabilities: [gpu]